// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings for `src/ros2_flutter_package.h`.
///
/// Regenerate bindings with `flutter pub run ffigen --config ffigen.yaml`.
///
class Ros2FlutterPackageBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Ros2FlutterPackageBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Ros2FlutterPackageBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void printStr() {
    return _printStr();
  }

  late final _printStrPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('printStr');
  late final _printStr = _printStrPtr.asFunction<void Function()>();

  int addTwo(
    int a,
    int b,
  ) {
    return _addTwo(
      a,
      b,
    );
  }

  late final _addTwoPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('addTwo');
  late final _addTwo = _addTwoPtr.asFunction<int Function(int, int)>();
}
